### ISSUE TITLE
[Bug]: Incorrect info text

### ISSUE THREAD

**Issue by TeraNovell** [Fuzss/arcanelanterns#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

Hey, the info text for the Brilliant Lantern is not displayed correctly. Can you please have a look at it? Thanks in advance ^^

![image](https://github.com/Fuzss/arcanelanterns/assets/16338782/f830289f-f4d2-43cf-8178-636b64dcf817)

STR:
* Search for the item and click on it in the JEI.

Forge: 47.2.0
JEI: 15.2.0.27

**Comment by Fuzss** [comment]
Thanks, fixed for 1.20.4. Won't backport.
