### ISSUE TITLE
[Bug]: Rabbits don't breed with love lantern

### ISSUE THREAD

**Issue by OscarHdez103** [Fuzss/arcanelanterns#5]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

A love lantern is meant to breed mobs and that work perfectly except for rabbits, I tested it with some other animals like sheep and it instantly worked everytime but with rabbits I have been waiting for a while and nothing is happening, I think it might be because most people don't breed rabbits so that funcionality wasn't implemented but it could just be that I am being extremely unlucky (Over 30 minutes testing rabbits)

**Comment by Fuzss** [comment]
Make sure there aren't too many animals nearby. Just having two rabbits nearby works perfectly fine, making them breed until there are at least six (?).
